# Generated by Django 2.0.7 on 2019-10-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0002_auto_20191004_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='el1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el1', to='colles.eleve'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='el2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el2', to='colles.eleve'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='el3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el3', to='colles.eleve'),
        ),
    ]
