# Generated by Django 2.0.7 on 2019-10-05 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0003_auto_20191004_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleur',
            name='id',
        ),
        migrations.AlterField(
            model_name='colleur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userc', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
