# Generated by Django 2.0.7 on 2019-10-05 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0004_auto_20191005_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='id',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usere', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
