# Generated by Django 2.0.7 on 2019-10-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0005_auto_20191005_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colle',
            name='creneau',
        ),
    ]
