# Generated by Django 2.0.7 on 2019-10-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0006_remove_colle_creneau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='colleur',
        ),
    ]
