# Generated by Django 2.0.7 on 2019-10-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0007_remove_creneau_colleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='colleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colles.colleur'),
        ),
        migrations.AlterField(
            model_name='colle',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colles.groupe'),
        ),
    ]
