# Generated by Django 2.0.7 on 2019-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0009_colle_creneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=1)),
                ('fichier', models.FileField(upload_to='programmes')),
            ],
        ),
        migrations.AlterField(
            model_name='colle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
