# Generated by Django 2.0.7 on 2019-10-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0010_auto_20191031_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='sem',
            new_name='semaine',
        ),
    ]
